export const PERMISSIONS = [
  {
    name: 'Dashboard:View',
    guard_name: 'web',
    group_name: 'Dashboard',
    parent_id: null,
    children: [],
    created_at: new Date(),
    updated_at: new Date(),
    roles: [],
  },
  {
    name: 'Dashboard:Edit',
    guard_name: 'web',
    group_name: 'Dashboard',
    parent_id: null,
    children: [],
    created_at: new Date(),
    updated_at: new Date(),
    roles: [],
  },
  {
    name: 'Billing Controls:View',
    guard_name: 'web',
    group_name: 'Billing Controls',
    parent_id: null,
    children: [],
    created_at: new Date(),
    updated_at: new Date(),
    roles: [],
  },
  {
    name: 'Billing Controls:Edit',
    guard_name: 'web',
    group_name: 'Billing Controls',
    parent_id: null,
    children: [],
    created_at: new Date(),
    updated_at: new Date(),
    roles: [],
  },
  {
    name: 'Plan Management:View',
    guard_name: 'web',
    group_name: 'Plan Management',
    parent_id: null,
    children: [],
    created_at: new Date(),
    updated_at: new Date(),
    roles: [],
  },
  {
    name: 'Plan Management:Edit',
    guard_name: 'web',
    group_name: 'Plan Management',
    parent_id: null,
    children: [],
    created_at: new Date(),
    updated_at: new Date(),
    roles: [],
  },
  {
    name: 'Role Management:View',
    guard_name: 'web',
    group_name: 'Role Management',
    parent_id: null,
    children: [],
    created_at: new Date(),
    updated_at: new Date(),
    roles: [],
  },
  {
    name: 'Role Management:Edit',
    guard_name: 'web',
    group_name: 'Role Management',
    parent_id: null,
    children: [],
    created_at: new Date(),
    updated_at: new Date(),
    roles: [],
  },
  {
    name: 'User Management:View',
    guard_name: 'web',
    group_name: 'User Management',
    parent_id: null,
    children: [],
    created_at: new Date(),
    updated_at: new Date(),
    roles: [],
  },
  {
    name: 'User Management:Edit',
    guard_name: 'web',
    group_name: 'User Management',
    parent_id: null,
    children: [],
    created_at: new Date(),
    updated_at: new Date(),
    roles: [],
  },
  {
    name: 'Dealer Management:View',
    guard_name: 'web',
    group_name: 'Dealer Management',
    parent_id: null,
    children: [],
    created_at: new Date(),
    updated_at: new Date(),
    roles: [],
  },
  {
    name: 'Dealer Management:Edit',
    guard_name: 'web',
    group_name: 'Dealer Management',
    parent_id: null,
    children: [],
    created_at: new Date(),
    updated_at: new Date(),
    roles: [],
  },
];
