// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v6.30.2
// source: auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "carvu";

export interface RequestAuthorizationPayload {
  email: string;
}

export interface ResponseAuthorizationPayload {
  accessToken: string;
  errors: string;
}

export const CARVU_PACKAGE_NAME = "carvu";

export interface AuthServiceClient {
  requestAuthorization(request: RequestAuthorizationPayload): Observable<ResponseAuthorizationPayload>;
}

export interface AuthServiceController {
  requestAuthorization(
    request: RequestAuthorizationPayload,
  ): Promise<ResponseAuthorizationPayload> | Observable<ResponseAuthorizationPayload> | ResponseAuthorizationPayload;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["requestAuthorization"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
